# Generated by roxytest: Do not edit by hand!

# File R/DEG.R: @testexamples

test_that("Function tcm.RunDEG() @ L36", {
  
  data <- tcm.LoadExampleDataset()
  
  # Get a subset of expression dataset
  ix <- c(1, 2, 61, 62)
  expr <- data$expr[, ix]
  group <- data$pdata$perturbagen[ix]
  
  # Run DEG analysis
  report <- tcm.RunDEG(expr, group = group, ref_group = group[3])
  head(report)
  
  # Run batch DEG analysis
  reports <- tcm.RunBatchDEG(expr, groups = group, ref_group = group[3])
  head(reports)
  
  identical(report, reports[[1]])
  expect_is(report, "data.table")
  expect_is(reports, "list")
  expect_identical(report, reports[[1]])
})

