# Generated by roxytest: Do not edit by hand!

# File R/"signature-search.R": @testexamples

test_that("Function tcm.SSwithCoreGx() @ L202", {
  
  data("data_logFC")
  query2 <- data_logFC[1:60, 1, drop = FALSE]
  txp <- tcm.SSwithCoreGx(query2, data_logFC[1:10])
  expect_is(txp, "data.frame")
})

