# Generated by roxytest: Do not edit by hand!

# File R/"load-data.R": @testexamples

test_that("Function tcm.LoadExampleDataset() @ L14", {
  
  x <- tcm.LoadExampleDataset()
  head(x$expr)
  head(x$pdata)
  expect_is(x, "list")
})


test_that("Function tcm.LoadAnalyzedDEG() @ L65", {
  
  
  # Firstly, check the dataset
  data("AnalyzedDEG")
  head(AnalyzedDEG)
  
  # Pick up what you want to load
  # A subset of AnalyzedDEG is recommended,
  # you can use %>%
  # Otherwise specify a subset of id column
  
  # e.g. head 5 sets
  head5_reports <- AnalyzedDEG %>%
    head(n = 5) %>%
    tcm.LoadAnalyzedDEG()
  
  # only the second
  one_report <- tcm.LoadAnalyzedDEG(2)
  expect_is(head5_reports, "list")
  expect_is(one_report, "data.frame")
})

