# Generated by roxytest: Do not edit by hand!

context("File R/deg_caller.R: @testexamples")

test_that("Function deg_caller() @ L32", {
  
  data <- load_example_dataset()
  
  # Get a subset of expression dataset
  ix <- c(1, 2, 61, 62)
  expr <- data$expr[, ix]
  group <- data$pdata$perturbagen[ix]
  
  # Run DEG analysis
  report <- deg_caller(expr, group = group, level = group[c(3, 1)])
  
  # Run batch DEG analysis
  reports <- deg_batch_caller(expr, groups = group, ref_group = group[3])
  
  identical(report, reports[[1]])
  expect_is(report, "data.table")
  expect_is(reports, "list")
})

