# Generated by roxytest: Do not edit by hand!

context("File R/get_sig_GO.R: @testexamples")

test_that("Function get_sig_GO() @ L17", {
  
  data("AnalyzedDEG")
  one_report <- load_analyzedDEG(1)
  deg <- subset(one_report, abs(logFC) > 1 & P.Value < 0.05)
  go <- get_sig_GO(deg, p.cutoff = 0.05, p.adj.cutoff = 0.5, n.path = 10)
  expect_is(go, "data.frame")
})

