# Generated by roxytest: Do not edit by hand!

context("File R/ss_CoreGx.R: @testexamples")

test_that("Function ss_CoreGx() @ L13", {
  
  data("data_logFC")
  query2 <- data_logFC[1:60, 1, drop = FALSE]
  txp <- ss_CoreGx(query2, data_logFC[1:10])
  expect_is(txp, "data.frame")
})

