# Generated by roxytest: Do not edit by hand!

context("File R/load_analyzedDEG.R: @testexamples")

test_that("Function load_analyzedDEG() @ L31", {
  
  
  # Firstly, check the dataset
  data("AnalyzedDEG")
  head(AnalyzedDEG)
  
  # Pick up what you want to load
  # A subset of AnalyzedDEG is recommended,
  # you can use %>%
  # Otherwise specify a subset of id column
  
  # e.g. head 5 sets
  head5_reports <- AnalyzedDEG %>%
    head(n = 5) %>%
    load_analyzedDEG()
  
  # only the second
  one_report <- load_analyzedDEG(2)
  expect_is(head5_reports, "list")
  expect_is(one_report, "data.frame")
})

